service: image-preprocessor

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: python3.8
  region: eu-central-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cloudformation:CreateStack"
        - "cloudformation:CreateChangeSet"
        - "cloudformation:ListStacks"
        - "cloudformation:UpdateStack"
        - "cloudformation:DescribeChangeSet"
        - "cloudformation:ExecuteChangeSet"
        - "s3:ListBucket"
      Resource:
        - "*"
    - Effect: Allow
      Action:
        - s3:*
      Resource: '*'

functions:
  resize:
    handler: handler.call
    environment:
      BUCKET: face-transfer-origin-images
      REGION: eu-central-1
#    events:
#      - http:
#          path: /{size}/{image}
#          method: get

# uncomment to create the resources:
#  Resources:
#    ResizedImages:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: face-transfer-origin-images

plugins:
  - serverless-python-requirements
